[2021-12-15 14:01:16,550]-[object.py]-[<module>]-[290]-12s: [INFO]-8s>> ces
[2021-12-15 14:01:16,551]-[object.py]-[<module>]-[291]-12s: [INFO]-8s>> hello
[2021-12-15 15:20:51,710]-[CasSystemScrapy.py]-[<module>]-[273]-12s: [INFO]-8s>> ces
[2021-12-15 15:20:51,711]-[CasSystemScrapy.py]-[<module>]-[274]-12s: [INFO]-8s>> hello
[2021-12-15 15:34:47,106]-[CasSystemScrapy.py]-[<module>]-[274]-12s: [INFO]-8s>> ces
[2021-12-15 15:34:47,107]-[CasSystemScrapy.py]-[<module>]-[275]-12s: [INFO]-8s>> hello
[2021-12-15 15:41:59,724]-[CasSystemScrapy.py]-[<module>]-[274]-12s: [INFO]-8s>> ces
[2021-12-15 15:41:59,725]-[CasSystemScrapy.py]-[<module>]-[275]-12s: [INFO]-8s>> hello
[2021-12-15 15:45:15,665]-[CasSystemScrapy.py]-[get_apply_data]-[269]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202112-4：Unexpected Error: list index out of range
[2021-12-15 15:57:40,719]-[CasSystemScrapy.py]-[get_apply_data]-[269]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202112-3：Unexpected Error: list index out of range
[2021-12-15 15:58:10,315]-[CasSystemScrapy.py]-[get_apply_data]-[269]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202112-2：Unexpected Error: list index out of range
[2021-12-15 16:06:55,268]-[CasSystemScrapy.py]-[<module>]-[275]-12s: [INFO]-8s>> ces
[2021-12-15 16:06:55,269]-[CasSystemScrapy.py]-[<module>]-[276]-12s: [INFO]-8s>> hello
[2021-12-15 16:07:34,955]-[CasSystemScrapy.py]-[get_apply_data]-[270]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202112-4：Unexpected Error: list index out of range
[2021-12-15 16:08:29,817]-[CasSystemScrapy.py]-[<module>]-[276]-12s: [INFO]-8s>> ces
[2021-12-15 16:08:29,818]-[CasSystemScrapy.py]-[<module>]-[277]-12s: [INFO]-8s>> hello
[2021-12-15 16:09:52,977]-[CasSystemScrapy.py]-[<module>]-[275]-12s: [INFO]-8s>> ces
[2021-12-15 16:09:52,978]-[CasSystemScrapy.py]-[<module>]-[276]-12s: [INFO]-8s>> hello
[2021-12-15 16:39:41,542]-[CasSystemScrapy.py]-[<module>]-[281]-12s: [INFO]-8s>> ces
[2021-12-15 16:39:41,543]-[CasSystemScrapy.py]-[<module>]-[282]-12s: [INFO]-8s>> hello
[2021-12-15 16:46:43,592]-[CasSystemScrapy.py]-[<module>]-[281]-12s: [INFO]-8s>> ces
[2021-12-15 16:46:43,594]-[CasSystemScrapy.py]-[<module>]-[282]-12s: [INFO]-8s>> hello
[2021-12-15 16:55:26,848]-[CasSystemScrapy.py]-[<module>]-[281]-12s: [INFO]-8s>> ces
[2021-12-15 16:55:26,849]-[CasSystemScrapy.py]-[<module>]-[282]-12s: [INFO]-8s>> hello
[2021-12-15 16:59:39,171]-[CasSystemScrapy.py]-[get_apply_data]-[276]-12s: [ERROR]-8s>> 解析明细信息出错，错误单号：GA-202111-1：Unexpected Error: list index out of range
